/**
 * Event Service — event management business logic.
 * FR-EVENT-001: Create event with name, date, venue, access mode.
 * FR-EVENT-002: Dual QR code generation (QR-A gallery, QR-B find-my-photos).
 * FR-EVENT-003: Regenerate/revoke QR codes.
 * FR-EVENT-004: Configurable gallery access mode.
 * FR-EVENT-005: Close/archive event lifecycle.
 * FR-EVENT-006: Event dashboard stats.
 * FR-PLAN-003: Enforce plan quotas (maxEvents) at creation time.
 *
 * SEC-001/SEC-002: Every query filters by tenantId from verified middleware.
 */

const Event = require('../models/Event');
const Photo = require('../models/Photo');
const Guest = require('../models/Guest');
const Match = require('../models/Match');
const Plan = require('../models/Plan');
const Tenant = require('../models/Tenant');
const { AppError } = require('../middleware/errorHandler');
const { logAction } = require('./audit.service');
const logger = require('../utils/logger');
const { EVENT_STATUS } = require('@photofolio/shared');

/**
 * Create a new event.
 * FR-EVENT-001: Event creation with all required fields.
 * FR-EVENT-002: Dual QR codes generated automatically.
 * FR-PLAN-003: Checks maxEvents quota from tenant's Plan (no hardcoded limits).
 *
 * @param {string} tenantId - Verified tenant ID from middleware.
 * @param {object} data - Validated event creation data.
 * @param {object} actor - Actor info for audit logging.
 * @returns {object} { event }
 */
async function createEvent(tenantId, data, actor) {
  // FR-PLAN-003: Check quota before allowing creation — read from Plan config
  const tenant = await Tenant.findById(tenantId);
  if (!tenant) {
    throw new AppError('Tenant not found.', 404, 'TENANT_NOT_FOUND');
  }

  if (tenant.planId) {
    const plan = await Plan.findById(tenant.planId);
    if (plan) {
      const currentEventCount = await Event.countDocuments({ tenantId });
      // NFR-MAINT-001: Quota comes from Plan config, never hardcoded
      if (currentEventCount >= plan.quotas.maxEvents) {
        throw new AppError(
          `Event limit reached. Your plan allows ${plan.quotas.maxEvents} events. ` +
          'Please upgrade your plan or archive existing events.',
          403,
          'EVENT_QUOTA_EXCEEDED'
        );
      }
    }
  }

  // FR-EVENT-001/002: Create event — QR tokens auto-generated by schema defaults
  const event = await Event.create({
    tenantId,
    name: data.name,
    date: {
      start: data.dateStart,
      end: data.dateEnd || null,
    },
    venue: data.venue || '',
    coverImage: data.coverImage || null,
    accessMode: data.accessMode,
    status: data.status || EVENT_STATUS.DRAFT,
  });

  // SEC-007: Audit log
  await logAction({
    ...actor,
    action: 'event.create',
    targetType: 'Event',
    targetId: event._id,
    metadata: { eventName: event.name, accessMode: event.accessMode },
  });

  logger.info({ tenantId, eventId: event._id }, 'Event created');

  return { event: event.toJSON() };
}

/**
 * List events for a tenant with optional filters.
 * SEC-001: Filters by tenantId at the data layer.
 *
 * @param {string} tenantId - Verified tenant ID from middleware.
 * @param {object} filters - { status, page, limit }
 * @returns {object} { events, pagination }
 */
async function listEvents(tenantId, filters = {}) {
  const { status, page = 1, limit = 20 } = filters;

  const query = { tenantId };
  if (status) {
    query.status = status;
  }

  const skip = (page - 1) * limit;
  const [events, total] = await Promise.all([
    Event.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit),
    Event.countDocuments(query),
  ]);

  return {
    events: events.map((e) => e.toJSON()),
    pagination: {
      page,
      limit,
      total,
      pages: Math.ceil(total / limit),
    },
  };
}

/**
 * Get a single event by ID with full dashboard stats.
 * FR-EVENT-006: Event dashboard — guest count, photo count, processing status, etc.
 * SEC-001: Filters by tenantId.
 *
 * @param {string} tenantId - Verified tenant ID from middleware.
 * @param {string} eventId - Event ID.
 * @returns {object} { event }
 */
async function getEvent(tenantId, eventId) {
  const event = await Event.findOne({ _id: eventId, tenantId });
  if (!event) {
    throw new AppError('Event not found.', 404, 'EVENT_NOT_FOUND');
  }

  // Compute event stats
  const [photoCount, processedPhotoCount, failedPhotoCount, guestCount, matchCount, storageAgg] = await Promise.all([
    Photo.countDocuments({ eventId }),
    Photo.countDocuments({ eventId, status: 'processed' }),
    Photo.countDocuments({ eventId, status: 'failed' }),
    Guest.countDocuments({ eventId, status: 'active' }),
    Match.countDocuments({ eventId }),
    Photo.aggregate([
      { $match: { eventId: event._id } },
      { $group: { _id: null, total: { $sum: '$sizeBytes' } } },
    ]),
  ]);

  const eventJson = event.toJSON();
  eventJson.stats = {
    photoCount,
    processedPhotoCount,
    failedPhotoCount,
    guestCount,
    matchCount,
    storageUsedBytes: storageAgg[0]?.total || 0,
  };

  return { event: eventJson };
}

/**
 * Update event details.
 * FR-EVENT-001/004: Update name, date, venue, access mode.
 * SEC-001: Filters by tenantId.
 *
 * @param {string} tenantId - Verified tenant ID from middleware.
 * @param {string} eventId - Event ID.
 * @param {object} data - Validated update data.
 * @param {object} actor - Actor info for audit logging.
 * @returns {object} { event }
 */
async function updateEvent(tenantId, eventId, data, actor) {
  const event = await Event.findOne({ _id: eventId, tenantId });
  if (!event) {
    throw new AppError('Event not found.', 404, 'EVENT_NOT_FOUND');
  }

  // Cannot update archived events
  if (event.status === EVENT_STATUS.ARCHIVED) {
    throw new AppError(
      'Cannot update an archived event.',
      400,
      'EVENT_ARCHIVED'
    );
  }

  const changes = {};
  const allowedFields = ['name', 'venue', 'coverImage', 'accessMode', 'status'];

  for (const field of allowedFields) {
    if (data[field] !== undefined && data[field] !== event[field]) {
      changes[field] = { from: event[field], to: data[field] };
      event[field] = data[field];
    }
  }

  // Handle date fields separately (nested object)
  if (data.dateStart !== undefined) {
    const oldStart = event.date.start?.toISOString();
    const newStart = new Date(data.dateStart).toISOString();
    if (oldStart !== newStart) {
      changes['date.start'] = { from: oldStart, to: newStart };
      event.date.start = data.dateStart;
    }
  }
  if (data.dateEnd !== undefined) {
    const oldEnd = event.date.end?.toISOString() || null;
    const newEnd = data.dateEnd ? new Date(data.dateEnd).toISOString() : null;
    if (oldEnd !== newEnd) {
      changes['date.end'] = { from: oldEnd, to: newEnd };
      event.date.end = data.dateEnd || null;
    }
  }

  if (Object.keys(changes).length === 0) {
    return { event: event.toJSON() };
  }

  await event.save();

  // SEC-007: Audit log
  await logAction({
    ...actor,
    action: 'event.update',
    targetType: 'Event',
    targetId: event._id,
    metadata: { changes },
  });

  logger.info({ tenantId, eventId: event._id }, 'Event updated');

  return { event: event.toJSON() };
}

/**
 * Regenerate a QR code token (QR-A or QR-B), invalidating the old one.
 * FR-EVENT-003: Photographer can regenerate/revoke a QR code if leaked.
 * SEC-001: Filters by tenantId.
 *
 * @param {string} tenantId - Verified tenant ID from middleware.
 * @param {string} eventId - Event ID.
 * @param {'A'|'B'} qrType - Which QR code to regenerate.
 * @param {object} actor - Actor info for audit logging.
 * @returns {object} { event }
 */
async function regenerateQrCode(tenantId, eventId, qrType, actor) {
  const event = await Event.findOne({ _id: eventId, tenantId });
  if (!event) {
    throw new AppError('Event not found.', 404, 'EVENT_NOT_FOUND');
  }

  if (event.status === EVENT_STATUS.ARCHIVED) {
    throw new AppError(
      'Cannot regenerate QR codes for an archived event.',
      400,
      'EVENT_ARCHIVED'
    );
  }

  const newToken = Event.generateQrToken();
  const tokenField = qrType === 'A' ? 'qrAToken' : 'qrBToken';
  const oldToken = event[tokenField];

  event[tokenField] = newToken;
  await event.save();

  // SEC-007: Audit log — QR regeneration is a security-relevant action
  await logAction({
    ...actor,
    action: 'event.regenerate_qr',
    targetType: 'Event',
    targetId: event._id,
    metadata: {
      qrType,
      // Log that old token was invalidated (don't log actual token values)
      action: `QR-${qrType} token regenerated, old token invalidated`,
    },
  });

  logger.info({ tenantId, eventId: event._id, qrType }, 'QR code regenerated');

  return { event: event.toJSON() };
}

/**
 * Archive an event.
 * FR-EVENT-005: Halts new guest onboarding, preserves existing galleries.
 * SEC-001: Filters by tenantId.
 *
 * @param {string} tenantId - Verified tenant ID from middleware.
 * @param {string} eventId - Event ID.
 * @param {object} actor - Actor info for audit logging.
 * @returns {object} { event }
 */
async function archiveEvent(tenantId, eventId, actor) {
  const event = await Event.findOne({ _id: eventId, tenantId });
  if (!event) {
    throw new AppError('Event not found.', 404, 'EVENT_NOT_FOUND');
  }

  if (event.status === EVENT_STATUS.ARCHIVED) {
    throw new AppError('Event is already archived.', 400, 'ALREADY_ARCHIVED');
  }

  event.status = EVENT_STATUS.ARCHIVED;
  await event.save();

  // SEC-007: Audit log
  await logAction({
    ...actor,
    action: 'event.archive',
    targetType: 'Event',
    targetId: event._id,
    metadata: { previousStatus: event.status },
  });

  logger.info({ tenantId, eventId: event._id }, 'Event archived');

  return { event: event.toJSON() };
}

module.exports = {
  createEvent,
  listEvents,
  getEvent,
  updateEvent,
  regenerateQrCode,
  archiveEvent,
};
